name: Reusable workflow to rollout to kubernetes cluster
on:
  workflow_call:
    inputs:
      stage:
        description: "Stage to deploy: *production|staging*"
        required: true
        type: string
      image:
        type: string
        required: true
      pod-name:
        type: string
        required: true
      namespace:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  k8s-rollout:
    name: Deploy to asura-stack (${{ inputs.stage }})
    runs-on: ubuntu-latest
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: Load KUBE_CONFIG to ENV
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          KUBE_CONFIG_DATA, eks/${{inputs.stage}}/kubeconfig-data
    - name: Deploy to EKS
      uses: getmiso/kubectl-aws-eks@master
      with:
        args: set image deployment/${{inputs.pod-name}} ${{inputs.pod-name}}=${{inputs.image}} -n ${{inputs.namespace}}
    - name: verify deployment
      uses: getmiso/kubectl-aws-eks@master
      with:
        args: rollout status deployment/${{inputs.pod-name}} -n ${{inputs.namespace}}